spring.application.name=gateway

# Server Port
server.port=9090

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Fetch registry every 30 seconds
eureka.client.registry-fetch-interval-seconds=30

# Heartbeat every 5 seconds
eureka.instance.lease-renewal-interval-in-seconds=5

# Expire instance after 10 seconds if no heartbeat
eureka.instance.lease-expiration-duration-in-seconds=10

# Actuator Configuration
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# API GATEWAY

spring.cloud.gateway.server.webflux.routes[0].id=employee-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://employee
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/employees/**

spring.cloud.gateway.server.webflux.routes[1].id=department-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://department
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/departments/**
